### ISSUE TITLE
Should we pin OS packages in the Dockerfiles?

### ISSUE THREAD

**Issue by chrismwendt** [sourcegraph/lsp-adapter#72]
Ubuntu recently released a new security patch for curl and removed the old package that we were depending on, and the quickest fix was to bump the version in #71.

We can continue to bump the versions as we notice builds failing, or we could unpin all the versions and trust that Ubuntu, for example, won't introduce breaking changes.

**Comment by nicksnyder** [comment]
Either way it requires a rebuild. I would like to try following the lint rule of explicitly pinning versions for at least some amount of time. The benefit is that we know exactly when things change and what changed. If something breaks we just need to look back at the commit history instead of wondering "what actually changed since last build?".

If we try it out for a while and it becomes annoying and we don't think it is valuable, we can stop.

**Comment by felixfbecker** [comment]
@chrismwendt moving this here

Lets compare:
The obvious downsides of pinning are
- We constantly need to update the versions
- Old builds or commits can never be rebuilt (locally nor in CI) because packages don't exist anymore. This strictly worse than having them _potentially_ not possible to rebuild because of a breaking change (potentially vs guaranteed).

What _benefits_ does it have for us to pin them? (I see none)

**Comment by chrismwendt** [comment]
`@nicksnyder` already mentioned a benefit:

> The benefit is that we know exactly when things change and what changed. If something breaks we just need to look back at the commit history instead of wondering "what actually changed since last build?".

I have yet to benefit from that, though, so I don't know how helpful that actually is. I know that we bump ~3 versions every couple weeks, which takes ~30 minutes each time.

The main reason I pinned OS packages was because Hadolint recommended it. In turn, the main reason for Hadolint was to ensure that pip packages were pinned (we saw that one bite us a while back).

I'm leaning towards unpinning all OS packages and trusting that the maintainer (Ubuntu, or whoever owns Node.js) doesn't make breaking changes. In a sense, they can't make breaking changes because they remove the old versions and force everyone to update!

**Comment by felixfbecker** [comment]
> The benefit is that we know exactly when things change and what changed. If something breaks we just need to look back at the commit history instead of wondering "what actually changed since last build?".

We can get that by inspecting the build logs, which every commit is linked to. It's not as nice as looking at a diff but given how rarely we gonna need to do it it's acceptable.

Example:
```
Setting up curl (7.47.0-1ubuntu2.8) ...
```
https://travis-ci.org/sourcegraph/lsp-adapter/jobs/391994504#L634

For me build reproducibility is the primary criterion to make a decision based off.

**Comment by felixfbecker** [comment]
> and trusting that the maintainer (Ubuntu, or whoever owns Node.js) doesn't make breaking changes. In a sense, they can't make breaking changes because they remove the old versions and force everyone to update!

I agree with this - for Node, we lock in to a major non-breaking version range by adding a specific repository to the repository lists.

**Comment by nicksnyder** [comment]
If it has been painful and/or a waste of time, then we should disable this lint rule and remove it.

**Comment by chrismwendt** [comment]
I'll unpin them.
